### PR TITLE
Added the ability to view release notes.

### PR DESCRIPTION
**Pull request by crockettt**

### CODE REVIEW

**Comment by wurmr** [comment]
Why merge around in a main repo instead of working on your own fork?

**Comment by crockettt** [comment]
@wurmr, I am trying to understand how the push/commit/pull requests work.  So if I have done this in the wrong order any directions would be much appreciated.  I was trying to bring the changes I made in the branch I was working on into the main branch. It is hopefully vetted and approved by @towlebooth  before it gets merged together.

**Comment by towlebooth** [comment]
We'll get there @crockettt.  I don't see any file changes as part of this PR - did you commit/push those changes to the branch first?

**Comment by towlebooth** [comment]
@wurmr We can introduce forking next.

**Comment by crockettt** [comment]
I did do a commit/push before I did the pull request here. I will go back and run the sync to check it and then look at the branch to see what happened.

**Comment by wurmr** [comment]
Well, when you get there: https://guides.github.com/activities/forking/

**Pull request closed without merging**
